## Первая домашняя работа или Goodbye python list, now numpy array is my best friend!

### Не очень большое предисловие (краткий список правил по домашним заданиям):

1. Эти домашние задания нужны в первую очередь для вас и вашего роста, как инженера Data Science.
За их невыполнение вас никто не осудит. Вы просто возьмёте от курса меньше, чем ребята
которые их прорешивали, закрепляя свои новые знания.
2. Не стоит фанатично выполнять эти домашки. Если у вас горят дедлайны по учебе,
то лучше закрывайте их и забудьте о домашках до того момента, когда у вас будет на это время.
3. Если возникают вопросы по ходу выполнения - в первую очередь погуглите! Если же чувствуется сильный затуп или вы хотите, чтобы ваше
решение задания проверили на качество, напишите кому-нибудь из организаторов курса (можно это сделать как в дискорде, так и в любой удобной для вас соцсети). Не знаю, насколько оперативно мы будем отвечать, но мы очень постараемся!
4. У данных домашек нет и не будет жесткого дедлайна, поэтому нет ничего страшного в том, что вы будете что-то не успевать. Но лучше всё же не откладывать в долгий ящик: цените свое время и наше, если учитывать факт проверки.
5. Единственное жесткое требование: по данным занятиям вести свой git-репозиторий, иначе вероятность того, что мы проверим вашу работу: 0 +-
эпсилон. За ответами на вопросы по типу: "Что это?", "Зачем это?", рекомендуем зайти на https://hellocsit.ru/.
6. Не исключается возможность работать с обычными файлами формата .py. Однако всё же стоит учитывать, что первые два-три домашних задания гораздо проще выполнять непосредственно в тетрадках jupyter, да и многие соревнования на Kaggle прорешиваются исключительно в них.
7. Часть домашних заданий будут разбираться через занятие-другое (если у большого количества людей возникнут проблемы, домашнее задание будем рассматривать и прорабатывать незамедлительно, на следующем же занятии).

Вы ничего не потеряете, если сделаете их позже, но разве не интереснее быть первопроходцем, чем идти за кем-то?)))

### Hello, python!

Данный топик посвящен тем людям, которые не работали или почти не работали с языком программирования python (если есть опыт
можно скипнуть).

1. Не бойтесь, если ваш опыт работы с данным языком не велик. Сейчас классический python - один из самых простых языков для
изучения. Если вы будете выполнять домашние задания и слушать лекции, то вы сможете приспособиться. Другое дело, что python - это чаще всего только инструмент для работы с фреймворками и библиотеками. С ними уже всё посложнее. С классическим библиотеками для ML мы вас познакомим, но если решите с чем-то поработать сами, то гугл и открытая документация каждой из библиотек вам в помощь.
2. Чтобы установить библиотеку на вашу компудахтер, пропишите `!pip` (у кого-то это может быть `!pip3`) `install <название библиотеки>` в терминале. В jupyter notebook можно прописать эти команды в ячейке кода с восклицательным знаком в начале и выполнить эту ячейку (Например: `!pip install numpy`).
3. Мы не будем посвящать отдельную лекцию по конструкциям и синтаксису обычного python, но будем о чем-то упоминать на занятиях
и в домашней работе (речь о list, dict comprehension, и т.д.). Все нюансы будут обосновываться и объясняться, однако одно и то же по 100 раз рассматривать что-то будет уже слишком так себе. Те, кто чувствует, что плохо знаком с python - будьте готовы, а главное - не стесняйтесь задавать вопросы, вникать и узнавать что-то новое =)
4. Небольшое напоминание о python: он не является строго типизированным языком, поэтому будьте с этим осторожнее. Чтобы проверить тип переменной, можете написать `print(type(<название переменной>))`.
#### Теперь можно наконец-то приступать к выполнению первых заданий, всем удачи и максимум удовольстия от курса!

### Задание 0: List и Dict Comprehension

Задания, представленные ниже, нужно сделать ТОЛЬКО с помощью list и dict comprehension. Они специально не трудные, чтобы дать вам возможность быстро разобраться (или же вспомнить), как это всё работает.

Примечание: все задачи должны решаться в ОДНУ строчку! (список с результатом должен создаваться с помощью одной строчки)

In [3]:
# выведите список, в котором будут хранится индексы всех букв 'a' в строке some_str
some_str = "Quick brown cat jumps over the lazy dog"
print([a for a in range(len(some_str)) if some_str[a]=='a'])

[13, 32]


In [4]:
# выведите список, в котором будут хранится все слова из some_str, в которых содержится буква 'н'
some_str = "Знаете почему парни, у которых отец из Непала, очень хороши собой? Они все непальцем деланные."
print([a for a in some_str.split() if a.count('н')>0])

['Знаете', 'парни,', 'очень', 'Они', 'непальцем', 'деланные.']


In [5]:
# Создайте список из 20 случайных чисел.
import random
a = [random.randint(1, 9999999) for x in range(0, 20)]
print(a)
# Переписать все элементы списка из прошлого задания в новый список следующим образом: сначала все четные, затем все
# нечетные.
print([x for x in a if x%2==0] + [x for x in a if x%2!=0])

[7330555, 7144580, 5829735, 4180263, 702373, 3646694, 5311744, 4822326, 1209907, 8584478, 568901, 2930639, 5692106, 6044401, 757897, 3398396, 4700117, 5618629, 9387347, 9839447]
[7144580, 3646694, 5311744, 4822326, 8584478, 5692106, 3398396, 7330555, 5829735, 4180263, 702373, 1209907, 568901, 2930639, 6044401, 757897, 4700117, 5618629, 9387347, 9839447]


In [6]:
# Создать матрицу (таблицу) при помощи list comprehension
n = 10
print([[0 for x in range(n)] for y in range(n)])

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [7]:
# Создайте список bin_str, который будет состоять из бинарного
# представления кода ASCII каждой буквы из строки some_str
# Например: ['0b1101011', '0b100001']
some_str = "welcome to ml homework!"
print([bin(ord(x)) for x in some_str])

['0b1110111', '0b1100101', '0b1101100', '0b1100011', '0b1101111', '0b1101101', '0b1100101', '0b100000', '0b1110100', '0b1101111', '0b100000', '0b1101101', '0b1101100', '0b100000', '0b1101000', '0b1101111', '0b1101101', '0b1100101', '0b1110111', '0b1101111', '0b1110010', '0b1101011', '0b100001']


In [8]:
# Далее создайте словарь, в котором каждая буква из some_str
# будет ключом, по которому можно получить соответствующее
# значение, являющееся бинарным представлением кода ASCII буквы
# (можно пользоваться созданным в прошлом задании списком bin_str)
# Например: [' ': '0b100000', 'e': '0b1100101']
some_str = "welcome to ml homework!"
print({x: bin(ord(x)) for x in some_str})


{'w': '0b1110111', 'e': '0b1100101', 'l': '0b1101100', 'c': '0b1100011', 'o': '0b1101111', 'm': '0b1101101', ' ': '0b100000', 't': '0b1110100', 'h': '0b1101000', 'r': '0b1110010', 'k': '0b1101011', '!': '0b100001'}


In [9]:
# Сделайте прошлое задание без использования списка bin_str
some_str = "welcome to ml homework!"
print({x: bin(ord(x)) for x in some_str})

{'w': '0b1110111', 'e': '0b1100101', 'l': '0b1101100', 'c': '0b1100011', 'o': '0b1101111', 'm': '0b1101101', ' ': '0b100000', 't': '0b1110100', 'h': '0b1101000', 'r': '0b1110010', 'k': '0b1101011', '!': '0b100001'}


In [10]:
# На основе списка с элементами от 100 до 1000 с шагом 50 (обозначим как list1), создайте словарь, в котором будут
# храниться результаты деления элемента из списка list1 на квадрат самого себя, а ключами будут значения из списка list1
print({x: x / (x**2) for x in range(100, 1000, 50)})

{100: 0.01, 150: 0.006666666666666667, 200: 0.005, 250: 0.004, 300: 0.0033333333333333335, 350: 0.002857142857142857, 400: 0.0025, 450: 0.0022222222222222222, 500: 0.002, 550: 0.0018181818181818182, 600: 0.0016666666666666668, 650: 0.0015384615384615385, 700: 0.0014285714285714286, 750: 0.0013333333333333333, 800: 0.00125, 850: 0.001176470588235294, 900: 0.0011111111111111111, 950: 0.0010526315789473684}


In [11]:
# БОНУСНОЕ ЗАДАНИЕ
some_str = """Я в своем познании настолько преисполнился, что я как будто бы уже сто триллионов миллиардов лет проживаю на триллионах и триллионах таких же планет, как эта Земля, мне этот мир абсолютно понятен, и я здесь ищу только одного - покоя, умиротворения и вот этой гармонии, от слияния с бесконечно вечным, от созерцания великого фрактального подобия и от вот этого замечательного всеединства существа, бесконечно вечного, куда ни посмотри, хоть вглубь - бесконечно малое, хоть ввысь - бесконечное большое, понимаешь? А ты мне опять со своим вот этим, иди суетись дальше, это твоё распределение, это твой путь и твой горизонт познания и ощущения твоей природы, он несоизмеримо мелок по сравнению с моим, понимаешь? Я как будто бы уже давно глубокий старец, бессмертный, ну или там уже почти бессмертный, который на этой планете от её самого зарождения, ещё когда только Солнце только-только сформировалось как звезда, и вот это газопылевое облако, вот, после взрыва, Солнца, когда оно вспыхнуло, как звезда, начало формировать вот эти коацерваты, планеты, понимаешь, я на этой Земле уже как будто почти пять миллиардов лет живу и знаю её вдоль и поперёк этот весь мир, а ты мне какие-то... мне не важно на твои тачки, на твои яхты, на твои квартиры, там, на твоё благо. Я был на этой планете бесконечным множеством, и круче Цезаря, и круче Гитлера, и круче всех великих, понимаешь, был, а где-то был конченым говном, ещё хуже, чем здесь. Я множество этих состояний чувствую. Где-то я был больше подобен растению, где-то я больше был подобен птице, там, червю, где-то был просто сгусток камня, это всё есть душа, понимаешь? Она имеет грани подобия совершенно многообразные, бесконечное множество. Но тебе этого не понять, поэтому ты езжай себе , мы в этом мире как бы живем разными ощущениями и разными стремлениями, соответственно, разное наше и место, разное и наше распределение. Тебе я желаю все самые крутые тачки чтоб были у тебя, и все самые лучше самки, если мало идей, обращайся ко мне, я тебе на каждую твою идею предложу сотню триллионов, как всё делать. Ну а я всё, я иду как глубокий старец,узревший вечное, прикоснувшийся к Божественному, сам стал богоподобен и устремлен в это бесконечное, и который в умиротворении, покое, гармонии, благодати, в этом сокровенном блаженстве пребывает, вовлеченный во всё и во вся, понимаешь, вот и всё, в этом наша разница. Так что я иду любоваться мирозданием, а ты идёшь преисполняться в ГРАНЯХ каких-то, вот и вся разница, понимаешь, ты не зришь это вечное бесконечное, оно тебе не нужно. Ну зато ты, так сказать, более активен, как вот этот дятел долбящий, или муравей, который очень активен в своей стезе, поэтому давай, наши пути здесь, конечно, имеют грани подобия, потому что всё едино, но я-то тебя прекрасно понимаю, а вот ты меня - вряд ли, потому что я как бы тебя в себе содержу, всю твою природу, она составляет одну маленькую там песчиночку, от того что есть во мне, вот и всё, поэтому давай, ступай, езжай, а я пошел наслаждаться прекрасным осенним закатом на берегу теплой южной реки. Всё, ступай, и я пойду. """
# создайте словарь ascended_dict, в котором каждому слову из строки some_str будет соответствовать число повторений этого слова в строке (допускается решение в сколь угодно строк, но попробуйте сделать с dict comprehension)
print({x: some_str.count(x) for x in some_str.split()})

{'Я': 5, 'в': 111, 'своем': 1, 'познании': 1, 'настолько': 1, 'преисполнился,': 1, 'что': 6, 'я': 53, 'как': 13, 'будто': 3, 'бы': 12, 'уже': 5, 'сто': 6, 'триллионов': 2, 'миллиардов': 2, 'лет': 2, 'проживаю': 1, 'на': 24, 'триллионах': 2, 'и': 155, 'таких': 1, 'же': 12, 'планет,': 1, 'эта': 1, 'Земля,': 1, 'мне': 6, 'этот': 3, 'мир': 8, 'абсолютно': 1, 'понятен,': 1, 'здесь': 3, 'ищу': 1, 'только': 5, 'одного': 1, '-': 12, 'покоя,': 1, 'умиротворения': 1, 'вот': 11, 'этой': 4, 'гармонии,': 2, 'от': 31, 'слияния': 1, 'с': 111, 'бесконечно': 7, 'вечным,': 1, 'созерцания': 1, 'великого': 1, 'фрактального': 1, 'подобия': 3, 'этого': 2, 'замечательного': 1, 'всеединства': 1, 'существа,': 1, 'вечного,': 1, 'куда': 1, 'ни': 33, 'посмотри,': 1, 'хоть': 2, 'вглубь': 1, 'малое,': 1, 'ввысь': 1, 'бесконечное': 4, 'большое,': 1, 'понимаешь?': 3, 'А': 2, 'ты': 11, 'опять': 1, 'со': 11, 'своим': 1, 'этим,': 1, 'иди': 1, 'суетись': 1, 'дальше,': 1, 'это': 21, 'твоё': 2, 'распределение,': 1, 'твой':

In [12]:
import numpy as np

### Задание 1 (Бинарные отношения):

Что такое бинарное отношение? Если сильно не углублятся в алгебру или дискретную математику, то бинарное отношение можно
понять как отображение одного элемента множества в другой (или факт того, как взаимодействует один объект на другой). Следовательно, оператором бинарного отношения можно считать функцию (от элемента множества), которая переводит этот элемент в другой элемент (возможно в себя) этого множества.

Кстати, функции на питоне определяются как `def <название функции> (<ее аргументы>)`.

Допустим, у нас есть игрушечный пример:

`def лень (`$some\_set_{i}$`)`, где $some\_set_{i}$ - это элемент множества $some\_set$, которое пусть будет заданно как {1, 2, 3, 4, 5}.
Функция лень должна считать интеграл некоторого распределения вероятности начала 3 мировой войны, но, к сожалению, искусственный интеллект настолько сильно развился, что функция стала черезчур ленивой для этого, и поэтому теперь она просто возвращает значение, которое ей было передано, отказываясь работать.

Функцию лень можно спокойно назвать оператором бинарного отношения, так как она получает на вход значение из множества $some\_set$
и возвращает значение из множества $some\_set$. То-есть, ее бинарное отношение будет иметь вид: {(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)}.
Давайте попробуем задать матрицу такого бинарного отношения с помощью инструментов numpy. Сделайте это задание функцией,
принимающей на вход множество бинарного отношения и колличество элементов в заданном множестве $some\_set$. Это нужно для обобщения
этого задания на произвольное бинарное отношение.

Пояснительная бригада: матрица бинарного отношения это двумерная матрица, элементы которой могут принимать значения 0 или 1, и которая показывает отображение с помощью бинарного оператора одного элемента множества в другой.

In [13]:
import numpy as np
def laziness(some_set):
    return some_set

some_set = [1, 2, 3, 4, 5]
n = 5

def matrix_init(n, mapping):
    a = np.array(mapping)
    b = []
    for i in a:
        b.append([i, i])
    return np.array(b)

a = matrix_init(len(some_set), some_set)

print(a)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


Для проверки правильности идущих далее заданий (а они будут связаны между собой) предлагаю написать небольшую функцию relation_init. Это творческое задание, поэтому способ реализации этой функции остается на усмотрение выполняющего: можно сразу ввести матрицу бинарного отношения, можно ввести множество бинарного отображение, можно придумать что-то другое.

Примечание: ввод значения с клавиатуры в питоне производится через функцию `input()`. Введеное значение будет иметь тип 'str',
поэтому, чтобы, например, получить целочисленное значение, к нему надо применить `int(<ваша переменная>)`. Чтобы считать несколько
значений, можно использовать оператор `input().split()`. Например: `a1, a2 = input.split()`. Превратить обе переменные в int можно
с помощью оператора `map()`, но это мы оставим вам на самостоятельное изучение. Для тех, кто реализует данное задание через файл формата .py, можете сугубо ради спортивного интереса вообще запариться и сделать это через `argparse`.

In [14]:
# Для функции ниже необходимо указать также аргументы
import numpy as np
def relation_init(n):
    arr = np.zeros((n,n))
    return arr
a = relation_init(5)
np.arange(1., a.size())

TypeError: 'int' object is not callable

Говорят, что бинарное отношение является рефлексивным, если все элементы матрицы этого бинарного отношения на ее главной диагонали равны единице (это означает, что существует отображение элемента множества в себя же). Отсюда можно сделать вывод, что бинарное отношение может быть и анти-рефлексивным: если на главной диагонали стоят все нули. В случае, если ни первое, ни второе не верно, то бинарное отношение считается просто "не рефлексивным". Давай напишем такую функцию, которая будет принимать на вход матрицу бинарного отношения и проверять факт
его рефлексивности или антирефлексивности, а если ничего из этого не выполняется, то будет говорить нам, что отношение не рефлексивно.

In [ ]:
def isRefl(a):
    if a.diagonal() == np.arange(1., a.size()):
        return " является рефлексивным"
    elif a.diagonal() == np.arange(1., a.size()):
        return "является антирефлексивным"
    else:
        return "не является рефлексивным"

a = relation_init(5)
isRefl(a)

Говорят, что бинарное отношение является симметричным, если для его матрицы $A$ справедливо: $A^T = A$. Если же все элементы вне главной диагонали матрицы $B$, определяемой как $B = A \odot A^T$, равны нулю, то бинарное отношение называют антисимметричным. Если оба условия выше не выполняются, отношение считается не симметричным. Напишите функцию, проверяющую этот факт, по аналогии с прошлым заданием. (Примечание-подсказка: символ $\odot$ означает поэлементное умножение)

In [ ]:
def isSymm(a):
    # TODO

isSymm(a)

Пришло время для еще одного занимательного факта о бинарном отношении: если $A^2 \leq A$, то бинарное отношение называют
транзитивным, иначе - не транзитивным. Дальше вы сами знаете, что дальше делать ))

In [ ]:
def isTran(a):
    # TODO

isTran(a)

Бинарные отношения можно также классифицировать, причем классификация бинарных отношений напрямую определяются их свойствами.

Виды бинарных отношений:

1. Рефлексивное транзитивное отношение называется отношением квазипорядка.
2. Рефлексивное симметричное транзитивное отношение называется отношением эквивалентности.
3. Рефлексивное антисимметричное транзитивное отношение называется отношением (частичного) порядка.
4. Антирефлексивное, антисимметричное и транзитивное отношение называется отношением строгого порядка.

Реализуйте функцию, которая будет классифицировать бинарное отношение по его входной матрице.

In [ ]:
def classifier (a):
    # TODO

Если вы все сделали правильно, то у вас должно получиться, что бинарное отношение лень являеся отношением эквивалентности.

### Задание 2 (Вероятная статистика):

Иннокентий работает в сверхсекретной организации над сверхсекретным проектом, из-за чего у него мало времени на учебу в университете,
а его преподаватель по математической статистике - это душный дед, который не понятно как ставит оценки на экзамене. Однако Никита не сдается, и он смог взломать компьютер своего преподавателя. Но, к его сожалению, соединение периодически обрывается, из-за чего он получает результаты экзамена только ста студентов и их уровень подготовки к экзамену (на момент сдачи), который представляет собой число в диапазоне [0, 1]. Это за все 50 лет, которые преподает дед.
По этим данным он пытается узнать несколько вещей: 
1. Какая оценка была самой вероятной среди тех 100 людей, результаты которых он получил в данный момент.
2. Какова была средняя оценка.
3. Чему равняется математическое ожидание оценок студентов.
4. Среднеквадратичное отклонение этих оценок и их дисперсия.
5. Какова его вероятность сдать экзамен (хотя бы на 3), которая вычисляется как (gcd(p, p-1) - 1) * 1000, где
p - это колличество людей среди этой сотни, которое сдало на 5.

Помогите ему это сделать.

"Взлом" компьютера и получение данных будет представлять собой 2 генератора случайных чисел, один из которых будет генерировать
целые числа в диапозоне [2, 5], а второй числа с плавающей точкой в диапозоне [0, 1].

In [ ]:
a = np.random.randint(low=2, high=6, size=100)
b = np.random.randn(100)
print(np.median(a))
print(np.mean(a))
print(np.var(b))
print(np.std(b))
print((np.gcd(np.count_nonzero(a==5), np.count_nonzero(a==5)-1) - 1) * 1000)

### Задание 3: Конченные шахматы

Иван - гроссмейстер по берляндским шахматам и сегодня он дает мастеркласс молодому поколению берляндцев.
Берляндские шахматы - это самая интересная игра в Берляндии и по совместительству единственная, так как грозный
мер Андрей запретил все другие игры. Но это никак не касается нашей истории.

В первую очередь игроку нужно расставить фигуры на доску размером n на n в шахматном порядке, все фигуры
игрока должны стоять только на белых клетках (клетка с координатами 0 0 будет всегда черной), если в клетке
есть фигура - в ней стоит 1, если фигуры нет - 0.

Примечание: для решения данного задания используйте только срезы массивов. Пример среза: a[:1]. Данная конструкция значит, что
мы берем все элементы массива a, начиная с 1 позиции.

Необходимо получить матрицу, определяющую доску берляндских шахмат

In [31]:
n = int(input())
x = np.zeros((n,n),dtype=int)
# (odd_rows, even_columns)
x[1::2,::2] = 1
# (even_rows, odd_columns)
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


Затем игрок выбирает любой столбец или строку и переставляет фигуры так, чтобы они были отсортированны в порядке неубывания или неворастания.
Реализуйте это кодом.

In [48]:
def srt(c_r, x, number, up): #c_r 0-столбец, 1- строка , up = 1 неубывание, up = 0 невозрастание
    if up == 0:
        if c_r == 1:
           x[number] = np.concatenate((np.ones(np.count_nonzero(x[number]==1)), np.zeros(len(x[number])-np.count_nonzero(x[number]==1))), axis=None)
        elif c_r == 0:
            x[::1, number] = np.concatenate((np.ones(np.count_nonzero(x[::1, number]==1)), np.zeros(len(x[::1, number])-np.count_nonzero(x[::1, number]==1))), axis=None)
    else:
        if c_r == 1:
           x[number] = np.concatenate((np.zeros(np.count_nonzero(x[number]==0)), np.ones(len(x[number])-np.count_nonzero(x[number]==0))), axis=None)
        elif c_r == 0:
            x[::1, number] = np.concatenate((np.zeros(np.count_nonzero(x[::1, number]==0)), np.ones(len(x[::1, number])-np.count_nonzero(x[::1, number]==0))), axis=None)
    return x
print(srt(0, x, 3, 0))

[[0 1 0 1 0]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [1 1 1 0 0]
 [0 1 0 0 0]]


Затем размерность доски уменьшается, путем удаления бокового столбца и боковой строки, и она становится размером n - 1 на n - 1.
Реализуйте это кодом.

In [49]:
def make_small(x):
    x = x[::1, 0:-1]
    x = x[:-1]
    return x
print(make_small(x))

[[0 1 0 1]
 [1 0 1 1]
 [0 1 0 1]
 [1 1 1 0]]


Для победы в этой игре, необходимо, чтобы при размерности доски 1 на 1 в ней осталась только одна 1. Попробуйте написать стратегию, которая будет всегда побеждать в берляндских шахматах
для доски любой размерности.

In [50]:
x = srt(1, x, 0, 0)
for i in range(n-1):
    x = make_small(x)
print(x)

[[1]]


### Задание 4 (Дополнительное):

Данные пункты предполагают использование вами смекалочки и подразумевают возможное использование функций NumPy, не
рассмотренных на очном занятии. Постарайтесь покопаться в документации NumPy, поискать возможные полезные функции и инструкции.

4.1 Пусть дан некоторый массив. Надо реализовать функцию, которая находит наиболее частое значение в массиве.

In [ ]:
z = np.random.randint(0,10,50)

4.2 А теперь напиши функцию, которая позволяет найти n наибольших значений в массиве

In [ ]:
z = np.arange(5000)
np.random.shuffle(z)
n = 5

4.3 Предполагая, что даны на вход два массива, реализовать функцию, которая осуществляет картезианское произведение

In [ ]:
def cartesian(arrays):
    #TODO

print(cartesian(([1, 2, 3], [4, 5])))

Прикрепи сюда пожалуйста картинку или гифку, которая описывала твоё состояние в процессе выполнения этого задания! :)